# Generated by Django 2.1.5 on 2019-02-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('monthly_goal', models.DecimalField(decimal_places=2, max_digits=2)),
                ('amt_raised', models.DecimalField(decimal_places=2, max_digits=2)),
                ('goal_acheived', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('money_donated', models.IntegerField()),
                ('donation_date', models.DateField()),
            ],
        ),
    ]
